# Ingress para el frontend — sin rewrite para que los assets /assets/*.js carguen correctamente
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexaflow-ingress-web
  namespace: nexaflow
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nexaweb-svc
                port:
                  number: 80
---
# Ingress para las APIs — con rewrite para eliminar el prefijo de path
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexaflow-ingress-api
  namespace: nexaflow
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /auth(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: nexaauth-svc
                port:
                  number: 80
          - path: /pos(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: nexapos-svc
                port:
                  number: 80
          - path: /book(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: nexabook-svc
                port:
                  number: 80
          - path: /insight(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: nexainsight-svc
                port:
                  number: 80
          - path: /ml(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: nexaml-svc
                port:
                  number: 80
