apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexapos
  namespace: nexaflow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nexapos
  template:
    metadata:
      labels:
        app: nexapos
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: nexapos
          image: nexaflow/nexapos:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: nexaflow-secrets
                  key: DB_CONNECTION
            - name: ASPNETCORE_URLS
              valueFrom:
                configMapKeyRef:
                  name: nexaflow-config
                  key: ASPNETCORE_URLS
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nexapos-svc
  namespace: nexaflow
spec:
  selector:
    app: nexapos
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30082
