apiVersion: v1
kind: Secret
metadata:
  name: nexaflow-secrets
  namespace: nexaflow
type: Opaque
# Valores en base64. Para regenerar: echo -n "valor" | base64
# DB_CONNECTION: Host=nexaflow-postgres;Database=NexosNexaFlow;Username=post_usr;Password=P3assW0e
# JWT_SECRET: nexaflow-prod-secret-min32chars!!
stringData:
  DB_CONNECTION: "Host=nexaflow-postgres;Database=NexosNexaFlow;Username=post_usr;Password=P3assW0e"
  DB_DSN_PYTHON: "postgresql://post_usr:P3assW0e@nexaflow-postgres:5432/NexosNexaFlow"
  JWT_SECRET: "nexaflow-prod-secret-min32chars!!"
  POSTGRES_PASSWORD: "P3assW0e"
  AWS_ACCESS_KEY_ID: "AKIAIOSFODNN7EXAMPLE"
  AWS_SECRET_ACCESS_KEY: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
  AWS_REGION: "us-east-1"
